# Generated by Django 4.2.8 on 2024-02-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_blog_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.CharField(max_length=128)),
                ('sender_thought', models.TextField()),
            ],
        ),
    ]
