# Generated by Django 4.2.8 on 2024-02-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_contact_alter_blog_blog_image_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='sender_email',
            field=models.CharField(default='', max_length=128),
        ),
    ]
