# Generated by Django 4.2.8 on 2024-02-28 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_alter_thought_sender_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='sender_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
